name: Windows-RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install Ngrok via Choco
      run: choco install ngrok -y

    - name: Authenticate Ngrok
      run: ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable RDP & Set Password
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" –Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        net user runneradmin AdminP@ss12345

    - name: Start Tunnel & Keep Alive
      run: |
        Write-Host "=========================================="
        Write-Host "Username : runneradmin"
        Write-Host "Password : AdminP@ss12345"
        Write-Host "=========================================="
        ngrok tcp 3389
