name: Windows-RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install Ngrok
      run: choco install ngrok
    - name: Authenticate Ngrok
      run: ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" –Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
    - name: Create Tunnel & Keep Alive
      run: |
        Start-Process ngrok -ArgumentList "tcp 3389"
        $i = 0
        while ($i -lt 360) {
          Start-Sleep -Seconds 60
          $i++
        }
